import execjs
from execjs import get
context = get()

# Adicione o suporte a JSON ao contexto
with open('JSON.js', 'r') as file:
    json_js = file.read()
    context.exec_(json_js)

# Crie um contexto JavaScript
context = execjs.compile("function add(x, y) {var data = JSON.parse(x); var items = data.result[0].Conteudo.DADOS; var listaChaveValor = [];  for (var i = 0; i < items.length; i++) {     var item = items[i];     var chave = item.item_descricao;     var valor = item.item_codigo;     listaChaveValor.push({ chave: valor }); }  return listaChaveValor;}")

# Execute uma função JavaScript no contexto
result = context.call("add", '{"result":[{"Resultado":"0","Mensagens":[],"MensagensSucesso":[],"Conteudo":{"TABELA":"ITEM","DADOS":[{"item_codigo":"0000000001","item_codigoreferencia":"0000000001","item_descricao":"BOBINA GALVALUME 0,43 X 1200 AZ150","item_qtdeseguranca":null,"item_precovenda":37.66,"item_tipo":"P","item_controlaestoque":"S","item_controlalote":"S","item_saldonegativo":"S","item_dtinclusao":"2022-11-14","item_dtalteracao":"2023-05-09","item_ativo":"S","item_dtbloqueio":null,"item_motivobloqueio":"","item_ativocompra":"S","item_dtbloqueiocompra":null,"item_motivobloqueiocompra":"","item_ativovenda":"S","item_dtbloqueiovenda":null,"item_motivobloqueiovenda":"","item_comprimento":null,"item_largura":null,"item_altura":null,"item_espessura":null,"item_pesoliquido":3.65,"item_pesobruto":3.65,"item_observacoes":"","unidade_codigo":"MT","grupoestoque_codigo":"004","classfiscal_codigo":"72106990","famcomercial_codigo":"0000000001","item_controlavalidade":"N","formulapv_codigo":0,"item_calculopeso":"2","anp_codigo":"","item_veiculo":"N","item_codigofabricante":"","item_codigointerno":"742","item_codigooriginal":"","item_aplicacao":"","item_marca":"","cest_codigo":"","subgrpest_codigo":"","subfamcom_codigo":"","item_codigolistaservico":"","item_codigotribmunicipio":"","item_codigoatividade":"","item_opcionalvenda":"N","item_obspedvenda":"N","fichatec_codigo":"","item_tipoobtencao":"CP","quest_codigo":"","item_variacao":"N","item_kit":"N","item_qtdemaxestoque":null,"item_descricaoresumida":"","item_apresentacaovolume":"","item_apresentacaounidade":"","item_taxa":"N","confvar_codigo":"","item_descricaonf":"BOBINA GALVALUME 0,43","item_xmlexportasemgtin":"N","item_tipocobranca":"U","item_calculometragem":"01","item_tipovariacao":"TT","item_variacaocomponente":"0008","item_comp1aleta":null,"item_espacamentoaleta":null,"item_comissaopadrao":null,"item_localizacaopadrao":"","item_vendaminima":null,"item_custoipipadrao":null,"item_devolucaoipipadrao":null,"item_equipamento":"N","item_tipovolume":"CX","fornec_codigoprincipal":"","item_margemlucro":32.98,"item_disponivelapp":"S","item_disponivelpdv":"S","item_tipovenda":"3","item_paginacatalogo":"","item_vendacasada":null,"item_limitedesconto":null,"item_descontolivre":null,"item_creficom":null,"item_importaseparado":"N","item_levarformulapvvariacao":"S","item_tipocalculoprecovenda":"01","item_diametro":null,"item_modelo":"","item_conversaom2telha":null,"item_custoopsemrequisicao":"N","centrocusto_codigo":0,"item_margemcentrocustofat":null,"item_impressaocarga":"01","item_precocomissaoaco":null,"item_calculacomissaoaco":"N","item_obspedcompra":"N","item_diametrointerno":null,"item_diametroexterno":null,"material_codigo":0}]}}]}', 3)
print(result)  # Output: 5
